
update SOLD_ITEM set SOLD_PRICE = SOLDPRICE;

update SOLD_ITEM set ITEM_PRICE_DETAILS_ID = ITEMPRICEDETAILS_ID;

alter table SOLD_ITEM DROP COLUMN SOLDPRICE;

alter table SOLD_ITEM DROP COLUMN ITEMPRICEDETAILS_ID;

commit;